apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:

      - name: rabbitmq

        image: rabbitmq:3-management

        ports:
        - containerPort: 5672

        - containerPort: 15672
        resources:

          requests:
            cpu: 100m
            memory: 192Mi

          limits:
            cpu: 250m
            memory: 384Mi

        volumeMounts:
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/conf.d/10-watermark.conf
          subPath: rabbitmq.conf

      volumes:
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config