apiVersion: apps/v1

kind: Deployment

metadata:
  name: miners

spec:

  replicas: 4

  selector:
    matchLabels:
      app: miner

  template:

    metadata:
      labels:
        app: miner

    spec:

      containers:
      - name: worker
        image:  bachi7/blockchain-worker4:latest

        command:
        - python3
        - worker.py

        resources:

          requests:
            cpu: 50m
            memory: 64Mi

          limits:
            cpu: 100m
            memory: 128Mi