FROM nvidia/cuda:12.9.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copia el binario compilado del punto 3
COPY minero .
RUN chmod +x ./minero

COPY worker.py .

CMD ["python3", "worker.py"]