apiVersion: apps/v1
kind: Deployment

metadata:
  name: locust
  namespace: observability

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: locust

  template:
    metadata:
      labels:
        app: locust
  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9646"
        prometheus.io/path: "/metrics"

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      nodeSelector:
        pool: monitoring

      tolerations:
      - key: monitoring
        operator: Equal
        value: "true"
        effect: NoSchedule

      containers:
        - name: locust
          securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL

          image: IMAGE_TAG
          imagePullPolicy: Always

          args:
            - -f
            - /home/locust/locustfile.py
            - --host=http://blockchain-nct.sdypp.svc.cluster.local
            - --web-host=0.0.0.0
          
          envFrom:
              - configMapRef:
                  name: locust-config
          ports:
            - name: metrics
              containerPort: 9646
              protocol: TCP

          env:
            - name: LOCUST_METRICS_PORT
              value: "9646"

            - name: TRANSACTION_ENDPOINT
              value: "/transaction"

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          
          readinessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 30