apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: observability
spec:
  type: ClusterIP

  selector:
    app: locust

  ports:
    - name: web
      port: 8089
      targetPort: 8089

    - name: metrics
      port: 9646
      targetPort: 9646