apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-gpu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-gpu-server
  template:
    metadata:
      labels:
        app: blockchain-gpu-server
    spec:
      containers:
        - name: gpu-server
          image: IMAGE_TAG
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              value: "34.46.108.71"
            - name: REDIS_HOST
              value: "35.224.56.210"
          resources:
            limits:
              nvidia.com/gpu: 1
