apiVersion: apps/v1
kind: Deployment
metadata:
  name: miners-cpu
spec:
  replicas: 0
  selector:
    matchLabels:
      app: miner-cpu
  template:
    metadata:
      labels:
        app: miner-cpu
    spec:
      containers:
      - name: worker-cpu
        image: bachi7/blockchain-worker-cpu:latest