apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sdypp
data:
  RABBITMQ_HOST: "rabbitmq"
  REDIS_HOST: "redis"
  DATABASE_URL: "postgres://entradas:entradas@postgres:5432/entradas"
  NCT_URL: "http://blockchain-nct"
  SESSION_PASSWORD: "change-me-in-production-at-least-32-chars!"
  NODE_ENV: "production"
