apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-worker-cpu
  namespace: sdypp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-worker-cpu
  template:
    metadata:
      labels:
        app: blockchain-worker-cpu
    spec:
      nodeSelector:
        pool: apps
      containers:
        - name: worker-cpu
          image: us-central1-docker.pkg.dev/tp-final-sdypp/sdypp/blockchain-worker-cpu:latest
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
