apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis

spec:
  replicas: 1
  strategy:
    type: Recreate # ESTO MATA EL POD VIEJO ANTES DE CREAR EL NUEVO
  selector:
    matchLabels:
      app: redis

  template:

    metadata:

      labels:
        app: redis

    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - knode10 # <--- EVITA EL NODO CON EL VOLUMEN TRABADO

      containers:

      - name: redis

        image: redis:7

        ports:

        - containerPort: 6379
        resources:

          requests:
            cpu: 50m
            memory: 64Mi

          limits:
            cpu: 128m
            memory: 128Mi

        volumeMounts:

        - name: redis-storage

          mountPath: /data

      volumes:

      - name: redis-storage

        persistentVolumeClaim:

          claimName: redis-pvc