name: "Pipeline 2 - Servicios Infraestructura"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "k8s/gke/infra/**"
  workflow_run:
    workflows: ["Pipeline 1 - Infraestructura GKE"]
    types: [completed]

permissions:
  id-token: write
  contents: read

jobs:
  gitleaks:
    uses: ./.github/workflows/gitleaks.yml

  deploy-infra:
    name: Deploy Redis + RabbitMQ
    needs: gitleaks
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: sdypp-cluster
          location: us-central1-a

      - name: Deploy namespace
        run: kubectl apply -f k8s/gke/namespaces.yaml

      - name: Sync RabbitMQ TLS secret from GitHub Secrets
        run: |
          echo "${{ secrets.RABBITMQ_TLS_CERT_B64 }}" | base64 -d > /tmp/rabbitmq-cert.pem
          echo "${{ secrets.RABBITMQ_TLS_KEY_B64 }}"  | base64 -d > /tmp/rabbitmq-key.pem
          kubectl create secret generic rabbitmq-tls -n sdypp \
            --from-file=rabbitmq-cert.pem=/tmp/rabbitmq-cert.pem \
            --from-file=rabbitmq-key.pem=/tmp/rabbitmq-key.pem \
            --dry-run=client -o yaml | kubectl apply -f -
          rm -f /tmp/rabbitmq-cert.pem /tmp/rabbitmq-key.pem

      - name: Deploy infrastructure services
        run: kubectl apply -f k8s/gke/infra/
      
      - name: Wait infrastructure
        run: |
          kubectl rollout status statefulset/rabbitmq -n sdypp --timeout=180s
          kubectl rollout status statefulset/redis -n sdypp --timeout=180s
